### ISSUE TITLE
Portainer seems to be unable to use longer passwords (or more complicated passwords)

### ISSUE THREAD

**Issue by katomaso** [Wakoma/Lokal#52]
Currently, we use CLI defined password in portainer deployment. We hash the password using `bcrypt` and print it directly into docker-compose.yml as shown below.

```yaml
  portainer:
    image: portainer/portainer-ce:latest
    user: "{{uid}}:{{gid_docker}}"
    command: --admin-password '{{password_admin|password_hash('bcrypt')}}'
```

The problem is that this does not work for out production password that is a bit longer and contains numbers. It works on shorter password (also with numbers).
